version: '3'

services:
  spring:
    image: audtncks2/spring-app
    ports:
      - "8080:8080"
  nginx:
    restart: always
    image: audtncks2/nginx
    ports:
      - "443:443"
    depends_on:
      - spring