version: '3'

services:
  nginx:
    restart: always
    image: audtncks2/nginx
    ports:
      - "8088:80"
    depends_on:
      - spring
  spring:
    image: audtncks2/spring-app
    ports:
      - "8080:8080"
