version: '3'

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8088:80"
    depends_on:
      - spring
  spring:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
