version: '3'

services:
  spring:
    image: audtncks2/spring-app
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
  nginx:
    restart: always
    image: audtncks2/nginx
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - spring

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
