spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: none
    username: none
    password: none

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      show-sql: true
