spring:
  datasource:
    url: jdbc:postgresql:dnd-7th-postgre.chjuel78c8av.ap-northeast-2.rds.amazonaws.com:5432/linkapp
    driver-class-name: org.postgresql.Driver
    username: root
    password: audtncks